#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-jfree
Version  : 1.0.0
Release  : 1
URL      : https://repo1.maven.org/maven2/jfree/jcommon/1.0.0/jcommon-1.0.0.jar
Source0  : https://repo1.maven.org/maven2/jfree/jcommon/1.0.0/jcommon-1.0.0.jar
Source1  : https://repo1.maven.org/maven2/jfree/jcommon/1.0.0/jcommon-1.0.0.pom
Source2  : https://repo1.maven.org/maven2/jfree/jfreechart/1.0.0/jfreechart-1.0.0.jar
Source3  : https://repo1.maven.org/maven2/jfree/jfreechart/1.0.0/jfreechart-1.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-3.0
Requires: mvn-jfree-data = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-jfree package.
Group: Data

%description data
data components for the mvn-jfree package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/jfree/jcommon/1.0.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/jfree/jcommon/1.0.0/jcommon-1.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/jfree/jcommon/1.0.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/jfree/jcommon/1.0.0/jcommon-1.0.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/jfree/jfreechart/1.0.0
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/jfree/jfreechart/1.0.0/jfreechart-1.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/jfree/jfreechart/1.0.0
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/jfree/jfreechart/1.0.0/jfreechart-1.0.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/jfree/jcommon/1.0.0/jcommon-1.0.0.jar
/usr/share/java/.m2/repository/jfree/jcommon/1.0.0/jcommon-1.0.0.pom
/usr/share/java/.m2/repository/jfree/jfreechart/1.0.0/jfreechart-1.0.0.jar
/usr/share/java/.m2/repository/jfree/jfreechart/1.0.0/jfreechart-1.0.0.pom
